.PHONY: all
all:
	../src/fcode detokenize ffb.fcode | diff ffb.fth -
	../src/fcode detokenize sslx-cg6.fcode | diff sslx-cg6.fth -
	#../src/fcode detokenize test-pci.fcode | diff test-pci.fth -
	../src/fcode detokenize -3 xvr100.fcode | diff xvr100.fth -
